//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbGoTripEntities1 : DbContext
    {
        public dbGoTripEntities1()
            : base("name=dbGoTripEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<tabloKurumsal> tabloKurumsals { get; set; }
        public virtual DbSet<tblAyarlar> tblAyarlars { get; set; }
        public virtual DbSet<tblBlog> tblBlogs { get; set; }
        public virtual DbSet<tblBlogKategori> tblBlogKategoris { get; set; }
        public virtual DbSet<tblGaleri> tblGaleris { get; set; }
        public virtual DbSet<tblGaleriKategori> tblGaleriKategoris { get; set; }
        public virtual DbSet<tblTurPaket> tblTurPakets { get; set; }
    }
}
