//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblGaleri
    {
        public int Id { get; set; }
        public string Baslik { get; set; }
        public Nullable<int> KategoriId { get; set; }
        public string Resim { get; set; }
    
        public virtual tblGaleriKategori tblGaleriKategori { get; set; }
    }
}
