//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTurPaket
    {
        public int Id { get; set; }
        public string Adi { get; set; }
        public string Fiyat { get; set; }
        public string Sure { get; set; }
        public string Lokasyon { get; set; }
        public string Resim { get; set; }
        public string Detay { get; set; }
    }
}
